version: "3.8"
services: 
  nginx: 
    container_name: nginx
    image: nginx:latest
    ports: 
    - target: 80
      published: 80
      protocol: tcp
    volumes: 
    - type: bind 
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on: 
    - front-end 

  front-end: 
    container_name: front_end_api
    image: docker.io/simharuk/front-end-api:latest
    build: ./front_end_api
    depends_on: 
    - numbers_api
    - day_api 
    - rollover_api

  numbers_api: 
    container_name: numbers_api
    image: docker.io/simharuk/numbers-api:latest
    build: ./numbers_api
    deploy:
      replicas: 3

  day_api:
    container_name: day_api 
    image: docker.io/simharuk/day-api:latest
    build: ./day_api 
    deploy: 
      replicas: 3
  
  rollover_api:
    container_name: rollover_api
    image: docker.io/simharuk/rollover-api:latest
    build: ./rollover_api
    deploy:
      replicas: 3
    depends_on:
    - numbers_api
    - day_api
    