all:
  children:
    # nginx:
    #   roles:
    #   - load-balancer
    swarm_managers:
      hosts:
        swarm-manager:
    swarm_workers:
      hosts:
        swarm-worker:

  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'