- hosts: nginx
  become: yes
  roles:
    - load-balancer

- hosts:
  - swarm_managers
  - swarm_workers
  become: yes
  roles:
    - docker-install

# - hosts:
#   - swarm_managers
#   become: yes
#   roles:
#     - swarm-setup

# - hosts:
#   - swarm_workers
#   become: yes
#   roles:
#     - swarm-join