---
# tasks file for swarm-worker

- name: "Add Worker to the Swarm"
  docker_swarm:
    state: join
    advertise_addr: swarm-worker
    join_token: "{{ hostvars['swarm-manager']['info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ 'swarm-manager:2377' ]